### ISSUE TITLE
Enable running the watch command from the `src` directory

### ISSUE THREAD

**Issue by Voles** [nickthesing/bb-watch#14]
Currently it is not possible to run the `$ bb-watch` command from the `src` directory. It does not find a `model.xml` file.

![screen shot 2017-08-07 at 14 57 23](https://user-images.githubusercontent.com/1725563/29027398-d5dbe1f0-7b80-11e7-8610-c08dd4ace4b2.png)

**Comment by nickthesing** [comment]
0.2.0
